### ISSUE TITLE
Cache webdav files

### ISSUE THREAD

**Issue by grrosminet** [aivanovski/keepassvault#247]
### Overview

Hi

It would be nice if you could implement a sort of caching for webdav files. With this, if network is unavailable, you could load the cached version (read only) so we still can have access to our passwords

**Comment by aivanovski** [comment]
Hi,

This functionality is already implemented in the app. But since I don't have WebDAV server, I will need some time to set it up and validate it. Maybe there is a some bug in it.

Please provide the steps to reproduce this issue. @grrosminet

**Comment by grrosminet** [comment]
It's right. Opening was so long when offline that I killed the app before. Sorry

**Comment by aivanovski** [comment]
@grrosminet Opening time should be equal the time of opening the same database from the file system. Application firstly opens file from cache and only after list of entries is displayed to the user, then application starts network request.
So, if time is not equal, then application may has a bug. But consider also fact that database decoding is done completely inside JVM runtime and for some databases it may take time.
