### ISSUE TITLE
[FEATURE] Support for ssh git access

### ISSUE THREAD

**Issue by reibax-marcus** [aivanovski/keepassvault#265]
### Overview

It would be very nice from the security and versatility point of view to be able to access git repos via ssh both with user/pass or with ssh key file authentication.

**Comment by aivanovski** [comment]
Hi,
It would be nice if this wasn't a tricky issue 😃 
When I added jgit library to this project it didn't work with ssh on Android. But it might work now, i will check it later.

I was wondering what you mean by "security" point of view? Is https access with token is considered less secure than ssh?
@reibax-marcus

**Comment by aivanovski** [comment]
After a quick check, looks lik jgit works with ssh.

**Comment by reibax-marcus** [comment]
Thank you very much for taking a moment to review the issue!
> 
> I was wondering what you mean by "security" point of view? Is https access with token is considered less secure than ssh? @reibax-marcus

Ah, yes... sorry. I wasn't explicit enough. https access with token is just as secure as ssh from the strict point of view of the protocol between keepassvault and the server. The thing is in order to have https with token you need to either be accessing a public git service, or have your own self-hosted git server like gitlab or gitea, which are relatively complex stacks that can have more vulnerabilities than just a simple linux box with ssh, which is really all you need to have a simple git server. It's that good old concept of simpler is better.

**Comment by aivanovski** [comment]
@reibax-marcus new build ssh support will be available in Fdroid and Google Play in a week. Google play probably in a couple of days

**Comment by reibax-marcus** [comment]
Thank you very much @aivanovski . I have tried to give it a try on version 1.7.0, but I don't seem to be able to make it work. I don't know if I am doing something wrong.

I have tried the following combinations:

```
ssh://user@ipaddress:/path/to/repo
```

```
ssh://user@ipaddress:/path/to/repo/kdbxfile.kdbx
```

```
ssh://user@url:port/path/to/repo
```

```
ssh://user@url:port/path/to/repo/kdbxfile.kdbx
```

And none of them seem to work.

**Comment by aivanovski** [comment]
Hi, @reibax-marcus 
Url should be the same as when you clone repository with `git clone ...`. 
There can be many reasons why the error occurs. Try to enable logging to file in the settings and check error. Please note, usually logging library write logs with a delay.
