### ISSUE TITLE
Be able to copy 2FA code

### ISSUE THREAD

**Issue by jeffmcneill** [aivanovski/keepassvault#275]
### Overview

This app is unusable by anyone who has two factor authentication enabled. There is no where and no way to copy that code.

**Comment by aivanovski** [comment]
Hi,
The TOTP code (e.g. 123 456) can be copied to the clipboard by clicking on it. Is that functionality you are looking for? @jeffmcneill

**Comment by jeffmcneill** [comment]
Only the TOTP Seed and 30;6 is available, not the actual code generated.

**Comment by aivanovski** [comment]
It's still not clear for me what your real use case is. Are you trying to change parameters in already existing TOTP url? Modification of OTP is available as plain text at the Editor screen. Unfortunately, there is no specific screen for that at the moment.
<img width="359" alt="Screenshot 2024-08-21 at 11 31 34" src="https://github.com/user-attachments/assets/f7176f26-db51-43ae-9c5d-cdb05d77e270">

**Comment by jeffmcneill** [comment]
I only see Title, UserName, Password, TOTP Seed, TOTP Settings. I do not see the actual temporary TOTP code. There is nowhere to click to get that TOTP code. I toggle hidden, and it is not there. I look around for settings, nothing to do with copying / viewing the temporary TOTP code that is needed for 2FA. I have a large, multi-year database, many entries of which have TOTP. However, I cannot seem to use this app to actually copy / view the TOTP codes.

**Comment by aivanovski** [comment]
Ok, I see, this app doesn't support "TOTP Seed", "TOTP Settings" fields. I'm actually not aware about existence of this fields.

This app supports "otp" field, it should have OTP url inside it (you may see it on screenshot above) and then TOTP code will be displayed.

**Comment by jeffmcneill** [comment]
![Uploading Screenshot_20240821_172143_KeePassVault.jpg…]()

**Comment by jeffmcneill** [comment]
![Screenshot_20240821_172143_KeePassVault](https://github.com/user-attachments/assets/f1dae0c6-13be-498d-b2ce-99903a52ce7d)

**Comment by aivanovski** [comment]
This is need to be implemented #276
