### ISSUE TITLE
What are the differences between debug, release, and test version of the app?

### ISSUE THREAD

**Issue by Adhjie** [aivanovski/keepassvault#286]
### Overview

keepassvault-debug.apk
18 MB 2024-10-19T19:52:58Z

keepassvault-release.apk
13.2 MB 2024-10-19T19:52:58Z

keepassvault-test.apk

There are these 3 .apk in GitHub release, which one should I use?
What are the differences between 3 of them?

**Comment by aivanovski** [comment]
- Release build is for regular users.
- Debug build is for development. It can be used on a daily basis but it includes some features hidden in the release build.
- Test build is for automated testing and is not intended for use by regular users.

**Comment by Adhjie** [comment]
Okay, understood.
BTW, could I make a new issue about bug that crash the app when it tries to open my database, or is this app for personal use only, and rarely get bug-fix, or feature request, as in this line from the readme:

> This app is orientated for my personal use. It may have some bugs, so please make a backups before using it.

I was trying this app because I currently met a bug in KeePassDX, but since this app also crashes I use KeePass2Android now. Should I report the bug and attached the fatal crash error from logfox here?

**Comment by aivanovski** [comment]
Sure, it is better if you make a report. But, if there is some hidden problem with your database file that crashes other clients, most likely I won't be able to fix it without the file itself. @Adhjie

**Comment by Adhjie** [comment]
The problem is purely KeePassVault crashing, and in logfox, its called 'Java Crash'.
My database is okay, I could open it in KeePass2Android. There is a problem in KeePassDX that forces close my database so that's a different issue.
Okay, I'll type a new bug report about this crash in another issue. I'll close this issue.
